### ISSUE TITLE
Criar entidades Usuário, Endereço e Família

### ISSUE THREAD

**Issue by alehRodrigues** [CaosEdd/Projeto_TTT#6]
Criar dentro da pasta  _**Projeto_TTT/Projeto_TTT.Domain/Entities**_ três pastas.

- [x] AggregateRoots
- [x] Aggregates
- [x] ObjectValues

- [x] Na pasta _AgreggateRoots_ criar uma classe chamada Usuario com as propredades especificadas em #4.
- [x] Na pasta _Aggregates_ criar uma classe chamada Endereco com as propriedades especificadas em #4.
- [x] Na pasta _Aggregates_ criar uma classe chamada Familia com as propriedades especificadas em #4.
- [x] Na pasta _ObjectValues criar uma classe chamada Cpf vazia e substituir o tipo da propriedade da classe Usuario de string para Cpf.
- [x] - [ ] Na pasta _ObjectValues criar uma classe chamada Cep vazia e substituir o tipo da propriedade da classe Endereco de string para Cep.

Criar dentro da pasta  _**Projeto_TTT/Projeto_TTT.Domain/Entities/ObjectValues**_ uma pasta chamada Enumarators.

- [x] Enumerators

Na pasta _Enumarators_ criar os seguintes enumeradores.

- [x] Genero
- [x] Orixa
- [x] Preferencia, substituir na classe Usuario a propriedade Salgado/Doce por Preferencia.
